//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:15:27 PM EDT 
//


package API.amazon.mws.xml.JAXB;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlowRate.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FlowRate">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="cubic_feet_per_second"/>
 *     &lt;enumeration value="cubic_feet_per_minute"/>
 *     &lt;enumeration value="cubic_feet_per_hour"/>
 *     &lt;enumeration value="cubic_inches_per_minute"/>
 *     &lt;enumeration value="cubic_meters_per_hour"/>
 *     &lt;enumeration value="liters_per_minute"/>
 *     &lt;enumeration value="liters_per_hour"/>
 *     &lt;enumeration value="cubic_centimeters_per_minute"/>
 *     &lt;enumeration value="cubic_centimeters_per_second"/>
 *     &lt;enumeration value="milliliters_per_minute"/>
 *     &lt;enumeration value="liters_per_second"/>
 *     &lt;enumeration value="cubic_meters_per_second"/>
 *     &lt;enumeration value="cubic_meters_per_minute"/>
 *     &lt;enumeration value="liters_per_day"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FlowRate")
@XmlEnum
public enum FlowRate {

    @XmlEnumValue("cubic_feet_per_second")
    CUBIC_FEET_PER_SECOND("cubic_feet_per_second"),
    @XmlEnumValue("cubic_feet_per_minute")
    CUBIC_FEET_PER_MINUTE("cubic_feet_per_minute"),
    @XmlEnumValue("cubic_feet_per_hour")
    CUBIC_FEET_PER_HOUR("cubic_feet_per_hour"),
    @XmlEnumValue("cubic_inches_per_minute")
    CUBIC_INCHES_PER_MINUTE("cubic_inches_per_minute"),
    @XmlEnumValue("cubic_meters_per_hour")
    CUBIC_METERS_PER_HOUR("cubic_meters_per_hour"),
    @XmlEnumValue("liters_per_minute")
    LITERS_PER_MINUTE("liters_per_minute"),
    @XmlEnumValue("liters_per_hour")
    LITERS_PER_HOUR("liters_per_hour"),
    @XmlEnumValue("cubic_centimeters_per_minute")
    CUBIC_CENTIMETERS_PER_MINUTE("cubic_centimeters_per_minute"),
    @XmlEnumValue("cubic_centimeters_per_second")
    CUBIC_CENTIMETERS_PER_SECOND("cubic_centimeters_per_second"),
    @XmlEnumValue("milliliters_per_minute")
    MILLILITERS_PER_MINUTE("milliliters_per_minute"),
    @XmlEnumValue("liters_per_second")
    LITERS_PER_SECOND("liters_per_second"),
    @XmlEnumValue("cubic_meters_per_second")
    CUBIC_METERS_PER_SECOND("cubic_meters_per_second"),
    @XmlEnumValue("cubic_meters_per_minute")
    CUBIC_METERS_PER_MINUTE("cubic_meters_per_minute"),
    @XmlEnumValue("liters_per_day")
    LITERS_PER_DAY("liters_per_day");
    private final String value;

    FlowRate(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FlowRate fromValue(String v) {
        for (FlowRate c: FlowRate.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
