//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:15:27 PM EDT 
//


package API.amazon.mws.xml.JAXB;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="clv"/>
 *               &lt;enumeration value="ac-3"/>
 *               &lt;enumeration value="dolby"/>
 *               &lt;enumeration value="thx"/>
 *               &lt;enumeration value="sega"/>
 *               &lt;enumeration value="nintendo"/>
 *               &lt;enumeration value="pal"/>
 *               &lt;enumeration value="ntsc"/>
 *               &lt;enumeration value="bw"/>
 *               &lt;enumeration value="color"/>
 *               &lt;enumeration value="subtitled"/>
 *               &lt;enumeration value="supratitled"/>
 *               &lt;enumeration value="dubbed"/>
 *               &lt;enumeration value="closed-captioned"/>
 *               &lt;enumeration value="threeD"/>
 *               &lt;enumeration value="abridged"/>
 *               &lt;enumeration value="laser_printed"/>
 *               &lt;enumeration value="photocopy"/>
 *               &lt;enumeration value="diskette35"/>
 *               &lt;enumeration value="diskette525"/>
 *               &lt;enumeration value="drama_enhanced"/>
 *               &lt;enumeration value="tarot"/>
 *               &lt;enumeration value="flash"/>
 *               &lt;enumeration value="classical"/>
 *               &lt;enumeration value="soundtrack"/>
 *               &lt;enumeration value="full-length"/>
 *               &lt;enumeration value="cd-single"/>
 *               &lt;enumeration value="import"/>
 *               &lt;enumeration value="cd-4"/>
 *               &lt;enumeration value="original_recording"/>
 *               &lt;enumeration value="remastered"/>
 *               &lt;enumeration value="reissued"/>
 *               &lt;enumeration value="remixes"/>
 *               &lt;enumeration value="bsides"/>
 *               &lt;enumeration value="extra_tracks"/>
 *               &lt;enumeration value="box_set"/>
 *               &lt;enumeration value="facsimile"/>
 *               &lt;enumeration value="gold_cd"/>
 *               &lt;enumeration value="explicit_lyrics"/>
 *               &lt;enumeration value="audiobook"/>
 *               &lt;enumeration value="widescreen"/>
 *               &lt;enumeration value="miniseries"/>
 *               &lt;enumeration value="dvt"/>
 *               &lt;enumeration value="hi-fidelity"/>
 *               &lt;enumeration value="collectors_edition"/>
 *               &lt;enumeration value="silent"/>
 *               &lt;enumeration value="directors_cut"/>
 *               &lt;enumeration value="full_screen"/>
 *               &lt;enumeration value="anamorphic"/>
 *               &lt;enumeration value="dvd_region"/>
 *               &lt;enumeration value="surround"/>
 *               &lt;enumeration value="dts_stereo"/>
 *               &lt;enumeration value="cx_encoding"/>
 *               &lt;enumeration value="animated"/>
 *               &lt;enumeration value="large_print"/>
 *               &lt;enumeration value="braille"/>
 *               &lt;enumeration value="enhanced"/>
 *               &lt;enumeration value="cast_recording"/>
 *               &lt;enumeration value="sacd"/>
 *               &lt;enumeration value="live"/>
 *               &lt;enumeration value="studio"/>
 *               &lt;enumeration value="secam"/>
 *               &lt;enumeration value="bargain_price"/>
 *               &lt;enumeration value="adobe_ebook_reader"/>
 *               &lt;enumeration value="everybook"/>
 *               &lt;enumeration value="microsoft_reader_desktop"/>
 *               &lt;enumeration value="limited_edition"/>
 *               &lt;enumeration value="electronic_software_download"/>
 *               &lt;enumeration value="extended_play"/>
 *               &lt;enumeration value="maxi_single"/>
 *               &lt;enumeration value="html"/>
 *               &lt;enumeration value="pdf"/>
 *               &lt;enumeration value="magazine_subscription"/>
 *               &lt;enumeration value="adult"/>
 *               &lt;enumeration value="wall_calendar"/>
 *               &lt;enumeration value="desk_calendar"/>
 *               &lt;enumeration value="box_calendar"/>
 *               &lt;enumeration value="engagement_calendar"/>
 *               &lt;enumeration value="mp3_audio"/>
 *               &lt;enumeration value="8_mm"/>
 *               &lt;enumeration value="adpcm"/>
 *               &lt;enumeration value="atrac3"/>
 *               &lt;enumeration value="digital_8"/>
 *               &lt;enumeration value="dvd_ram"/>
 *               &lt;enumeration value="dvd_rom"/>
 *               &lt;enumeration value="dvd_video"/>
 *               &lt;enumeration value="hi_8"/>
 *               &lt;enumeration value="minidisc"/>
 *               &lt;enumeration value="minidv"/>
 *               &lt;enumeration value="mpeg_2_5"/>
 *               &lt;enumeration value="real_audio"/>
 *               &lt;enumeration value="realaudio_g2"/>
 *               &lt;enumeration value="vhs"/>
 *               &lt;enumeration value="vhs_c"/>
 *               &lt;enumeration value="uk_import"/>
 *               &lt;enumeration value="us_import"/>
 *               &lt;enumeration value="best_of"/>
 *               &lt;enumeration value="double_lp"/>
 *               &lt;enumeration value="highlights"/>
 *               &lt;enumeration value="complete"/>
 *               &lt;enumeration value="hybrid_sacd"/>
 *               &lt;enumeration value="newspaper_subscription"/>
 *               &lt;enumeration value="palm_ebook_reader"/>
 *               &lt;enumeration value="unknown_format"/>
 *               &lt;enumeration value="playstation"/>
 *               &lt;enumeration value="letterboxed"/>
 *               &lt;enumeration value="unabridged"/>
 *               &lt;enumeration value="processor386"/>
 *               &lt;enumeration value="compilation"/>
 *               &lt;enumeration value="cd-6"/>
 *               &lt;enumeration value="authorized_bootleg"/>
 *               &lt;enumeration value="double_cd"/>
 *               &lt;enumeration value="karaoke"/>
 *               &lt;enumeration value="restored"/>
 *               &lt;enumeration value="special_edition"/>
 *               &lt;enumeration value="digital_sound"/>
 *               &lt;enumeration value="criterion"/>
 *               &lt;enumeration value="cutout"/>
 *               &lt;enumeration value="clean"/>
 *               &lt;enumeration value="copy_protected_cd"/>
 *               &lt;enumeration value="newsletter_subscription"/>
 *               &lt;enumeration value="deluxe_edition"/>
 *               &lt;enumeration value="limited_collectors_edition"/>
 *               &lt;enumeration value="special_extended_version"/>
 *               &lt;enumeration value="special_limited_edition"/>
 *               &lt;enumeration value="ultimate_edition"/>
 *               &lt;enumeration value="aus_import"/>
 *               &lt;enumeration value="ca_import"/>
 *               &lt;enumeration value="jp_import"/>
 *               &lt;enumeration value="mono"/>
 *               &lt;enumeration value="wav"/>
 *               &lt;enumeration value="wma"/>
 *               &lt;enumeration value="vqf"/>
 *               &lt;enumeration value="aiff"/>
 *               &lt;enumeration value="mpeg"/>
 *               &lt;enumeration value="avi"/>
 *               &lt;enumeration value="memory_stick"/>
 *               &lt;enumeration value="compact_flash"/>
 *               &lt;enumeration value="cd"/>
 *               &lt;enumeration value="smart_media"/>
 *               &lt;enumeration value="xd_card"/>
 *               &lt;enumeration value="illustrated"/>
 *               &lt;enumeration value="student_edition"/>
 *               &lt;enumeration value="teachers_edition"/>
 *               &lt;enumeration value="rental"/>
 *               &lt;enumeration value="ali"/>
 *               &lt;enumeration value="alx"/>
 *               &lt;enumeration value="cab"/>
 *               &lt;enumeration value="cod"/>
 *               &lt;enumeration value="csv"/>
 *               &lt;enumeration value="dff"/>
 *               &lt;enumeration value="doc"/>
 *               &lt;enumeration value="exe"/>
 *               &lt;enumeration value="gif"/>
 *               &lt;enumeration value="ipk"/>
 *               &lt;enumeration value="jad"/>
 *               &lt;enumeration value="jar"/>
 *               &lt;enumeration value="jpg"/>
 *               &lt;enumeration value="mdb"/>
 *               &lt;enumeration value="mde"/>
 *               &lt;enumeration value="pdb"/>
 *               &lt;enumeration value="pqa"/>
 *               &lt;enumeration value="prc"/>
 *               &lt;enumeration value="prn"/>
 *               &lt;enumeration value="rar"/>
 *               &lt;enumeration value="sis"/>
 *               &lt;enumeration value="sit"/>
 *               &lt;enumeration value="tiff"/>
 *               &lt;enumeration value="txt"/>
 *               &lt;enumeration value="wks"/>
 *               &lt;enumeration value="xls"/>
 *               &lt;enumeration value="xml"/>
 *               &lt;enumeration value="zip"/>
 *               &lt;enumeration value="amazon_ebook_reader"/>
 *               &lt;enumeration value="bookplus_reader"/>
 *               &lt;enumeration value="registration_code"/>
 *               &lt;enumeration value="cd_rom"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="delete" type="{}BooleanType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "format")
public class Format {

    protected List<String> value;
    @XmlAttribute(name = "delete")
    protected BooleanType delete;

    /**
     * Gets the value of the value property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the value property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValue() {
        if (value == null) {
            value = new ArrayList<String>();
        }
        return this.value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setDelete(BooleanType value) {
        this.delete = value;
    }

}
