//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:15:27 PM EDT 
//


package API.amazon.mws.xml.JAXB;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MerchantFulfillmentOrderID" type="{}FortyStringNotNull"/>
 *         &lt;element name="DisplayableOrderID" type="{}FortyStringNotNull"/>
 *         &lt;element name="DisplayableOrderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DisplayableOrderComment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeliverySLA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FulfillmentPolicy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FulfillmentMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DestinationAddress" type="{}AddressType"/>
 *         &lt;element name="Item" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MerchantSKU" type="{}SKUType"/>
 *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="MerchantFulfillmentOrderItemID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="GiftMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DisplayableComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="FulfillmentNetworkSKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OrderItemDisposition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "merchantFulfillmentOrderID",
    "displayableOrderID",
    "displayableOrderDate",
    "displayableOrderComment",
    "deliverySLA",
    "fulfillmentPolicy",
    "fulfillmentMethod",
    "destinationAddress",
    "item"
})
@XmlRootElement(name = "FulfillmentOrderRequest")
public class FulfillmentOrderRequest {

    @XmlElement(name = "MerchantFulfillmentOrderID", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String merchantFulfillmentOrderID;
    @XmlElement(name = "DisplayableOrderID", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String displayableOrderID;
    @XmlElement(name = "DisplayableOrderDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar displayableOrderDate;
    @XmlElement(name = "DisplayableOrderComment", required = true)
    protected String displayableOrderComment;
    @XmlElement(name = "DeliverySLA", required = true)
    protected String deliverySLA;
    @XmlElement(name = "FulfillmentPolicy")
    protected String fulfillmentPolicy;
    @XmlElement(name = "FulfillmentMethod")
    protected String fulfillmentMethod;
    @XmlElement(name = "DestinationAddress", required = true)
    protected AddressType destinationAddress;
    @XmlElement(name = "Item", required = true)
    protected List<FulfillmentOrderRequest.Item> item;

    /**
     * Gets the value of the merchantFulfillmentOrderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantFulfillmentOrderID() {
        return merchantFulfillmentOrderID;
    }

    /**
     * Sets the value of the merchantFulfillmentOrderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantFulfillmentOrderID(String value) {
        this.merchantFulfillmentOrderID = value;
    }

    /**
     * Gets the value of the displayableOrderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayableOrderID() {
        return displayableOrderID;
    }

    /**
     * Sets the value of the displayableOrderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayableOrderID(String value) {
        this.displayableOrderID = value;
    }

    /**
     * Gets the value of the displayableOrderDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDisplayableOrderDate() {
        return displayableOrderDate;
    }

    /**
     * Sets the value of the displayableOrderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDisplayableOrderDate(XMLGregorianCalendar value) {
        this.displayableOrderDate = value;
    }

    /**
     * Gets the value of the displayableOrderComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayableOrderComment() {
        return displayableOrderComment;
    }

    /**
     * Sets the value of the displayableOrderComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayableOrderComment(String value) {
        this.displayableOrderComment = value;
    }

    /**
     * Gets the value of the deliverySLA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliverySLA() {
        return deliverySLA;
    }

    /**
     * Sets the value of the deliverySLA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliverySLA(String value) {
        this.deliverySLA = value;
    }

    /**
     * Gets the value of the fulfillmentPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentPolicy() {
        return fulfillmentPolicy;
    }

    /**
     * Sets the value of the fulfillmentPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentPolicy(String value) {
        this.fulfillmentPolicy = value;
    }

    /**
     * Gets the value of the fulfillmentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentMethod() {
        return fulfillmentMethod;
    }

    /**
     * Sets the value of the fulfillmentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentMethod(String value) {
        this.fulfillmentMethod = value;
    }

    /**
     * Gets the value of the destinationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getDestinationAddress() {
        return destinationAddress;
    }

    /**
     * Sets the value of the destinationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setDestinationAddress(AddressType value) {
        this.destinationAddress = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FulfillmentOrderRequest.Item }
     * 
     * 
     */
    public List<FulfillmentOrderRequest.Item> getItem() {
        if (item == null) {
            item = new ArrayList<FulfillmentOrderRequest.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MerchantSKU" type="{}SKUType"/>
     *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="MerchantFulfillmentOrderItemID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="GiftMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DisplayableComment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="FulfillmentNetworkSKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OrderItemDisposition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "merchantSKU",
        "quantity",
        "merchantFulfillmentOrderItemID",
        "giftMessage",
        "displayableComment",
        "fulfillmentNetworkSKU",
        "orderItemDisposition"
    })
    public static class Item {

        @XmlElement(name = "MerchantSKU", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String merchantSKU;
        @XmlElement(name = "Quantity", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger quantity;
        @XmlElement(name = "MerchantFulfillmentOrderItemID", required = true)
        protected String merchantFulfillmentOrderItemID;
        @XmlElement(name = "GiftMessage")
        protected String giftMessage;
        @XmlElement(name = "DisplayableComment")
        protected String displayableComment;
        @XmlElement(name = "FulfillmentNetworkSKU")
        protected String fulfillmentNetworkSKU;
        @XmlElement(name = "OrderItemDisposition")
        protected String orderItemDisposition;

        /**
         * Gets the value of the merchantSKU property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMerchantSKU() {
            return merchantSKU;
        }

        /**
         * Sets the value of the merchantSKU property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMerchantSKU(String value) {
            this.merchantSKU = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setQuantity(BigInteger value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the merchantFulfillmentOrderItemID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMerchantFulfillmentOrderItemID() {
            return merchantFulfillmentOrderItemID;
        }

        /**
         * Sets the value of the merchantFulfillmentOrderItemID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMerchantFulfillmentOrderItemID(String value) {
            this.merchantFulfillmentOrderItemID = value;
        }

        /**
         * Gets the value of the giftMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftMessage() {
            return giftMessage;
        }

        /**
         * Sets the value of the giftMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftMessage(String value) {
            this.giftMessage = value;
        }

        /**
         * Gets the value of the displayableComment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayableComment() {
            return displayableComment;
        }

        /**
         * Sets the value of the displayableComment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayableComment(String value) {
            this.displayableComment = value;
        }

        /**
         * Gets the value of the fulfillmentNetworkSKU property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFulfillmentNetworkSKU() {
            return fulfillmentNetworkSKU;
        }

        /**
         * Sets the value of the fulfillmentNetworkSKU property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFulfillmentNetworkSKU(String value) {
            this.fulfillmentNetworkSKU = value;
        }

        /**
         * Gets the value of the orderItemDisposition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderItemDisposition() {
            return orderItemDisposition;
        }

        /**
         * Sets the value of the orderItemDisposition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderItemDisposition(String value) {
            this.orderItemDisposition = value;
        }

    }

}
