//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:15:27 PM EDT 
//


package API.amazon.mws.xml.JAXB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="package_weight" type="{}WeightValueNoDelete" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="package_dimensions" type="{}PackageDimensionsType"/>
 *           &lt;element name="standard_item_package" type="{}StandardItemPackageType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="delete" type="{}BooleanType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "packageWeight",
    "packageDimensions",
    "standardItemPackage"
})
@XmlRootElement(name = "ItemPackage")
public class ItemPackage {

    @XmlElement(name = "package_weight")
    protected WeightValueNoDelete packageWeight;
    @XmlElement(name = "package_dimensions")
    protected PackageDimensionsType packageDimensions;
    @XmlElement(name = "standard_item_package")
    protected StandardItemPackageType standardItemPackage;
    @XmlAttribute(name = "delete")
    protected BooleanType delete;

    /**
     * Gets the value of the packageWeight property.
     * 
     * @return
     *     possible object is
     *     {@link WeightValueNoDelete }
     *     
     */
    public WeightValueNoDelete getPackageWeight() {
        return packageWeight;
    }

    /**
     * Sets the value of the packageWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightValueNoDelete }
     *     
     */
    public void setPackageWeight(WeightValueNoDelete value) {
        this.packageWeight = value;
    }

    /**
     * Gets the value of the packageDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link PackageDimensionsType }
     *     
     */
    public PackageDimensionsType getPackageDimensions() {
        return packageDimensions;
    }

    /**
     * Sets the value of the packageDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageDimensionsType }
     *     
     */
    public void setPackageDimensions(PackageDimensionsType value) {
        this.packageDimensions = value;
    }

    /**
     * Gets the value of the standardItemPackage property.
     * 
     * @return
     *     possible object is
     *     {@link StandardItemPackageType }
     *     
     */
    public StandardItemPackageType getStandardItemPackage() {
        return standardItemPackage;
    }

    /**
     * Sets the value of the standardItemPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardItemPackageType }
     *     
     */
    public void setStandardItemPackage(StandardItemPackageType value) {
        this.standardItemPackage = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanType }
     *     
     */
    public BooleanType getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanType }
     *     
     */
    public void setDelete(BooleanType value) {
        this.delete = value;
    }

}
