//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:15:27 PM EDT 
//


package API.amazon.mws.xml.JAXB;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sku">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="value" type="{}ItemFortyStringNotNull"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MarketplaceData" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="launch_date" type="{}DateValue" minOccurs="0"/>
 *                 &lt;/all>
 *                 &lt;attribute name="market_name" use="required" type="{}ItemStringNotNull" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DescriptionData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="can_be_giftmessaged" type="{}BooleanValue" minOccurs="0"/>
 *                   &lt;element name="can_be_giftwrapped" type="{}BooleanValue" minOccurs="0"/>
 *                   &lt;element name="ean" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="value" type="{}StandardIdString" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="delete" type="{}BooleanType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="isbn" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="value">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *                                   &lt;minLength value="10"/>
 *                                   &lt;maxLength value="13"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="delete" type="{}BooleanType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="offering_condition" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="value" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *                                   &lt;enumeration value="New"/>
 *                                   &lt;enumeration value="Used"/>
 *                                   &lt;enumeration value="Collectible"/>
 *                                   &lt;enumeration value="Refurbished"/>
 *                                   &lt;enumeration value="Club"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="delete" type="{}BooleanType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="offering_subcondition" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="value" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *                                   &lt;enumeration value="New"/>
 *                                   &lt;enumeration value="LikeNew"/>
 *                                   &lt;enumeration value="VeryGood"/>
 *                                   &lt;enumeration value="Good"/>
 *                                   &lt;enumeration value="Acceptable"/>
 *                                   &lt;enumeration value="Refurbished"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="delete" type="{}BooleanType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="product_tax_code" type="{}StringValue" minOccurs="0"/>
 *                   &lt;element name="upc" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="value" type="{}StandardIdString" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="delete" type="{}BooleanType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AdditionalData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='lax' maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sku",
    "marketplaceData",
    "descriptionData",
    "additionalData"
})
@XmlRootElement(name = "Offer")
public class Offer {

    @XmlElement(required = true)
    protected Offer.Sku sku;
    @XmlElement(name = "MarketplaceData")
    protected List<Offer.MarketplaceData> marketplaceData;
    @XmlElement(name = "DescriptionData")
    protected Offer.DescriptionData descriptionData;
    @XmlElement(name = "AdditionalData")
    protected Offer.AdditionalData additionalData;

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link Offer.Sku }
     *     
     */
    public Offer.Sku getSku() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offer.Sku }
     *     
     */
    public void setSku(Offer.Sku value) {
        this.sku = value;
    }

    /**
     * Gets the value of the marketplaceData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marketplaceData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarketplaceData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Offer.MarketplaceData }
     * 
     * 
     */
    public List<Offer.MarketplaceData> getMarketplaceData() {
        if (marketplaceData == null) {
            marketplaceData = new ArrayList<Offer.MarketplaceData>();
        }
        return this.marketplaceData;
    }

    /**
     * Gets the value of the descriptionData property.
     * 
     * @return
     *     possible object is
     *     {@link Offer.DescriptionData }
     *     
     */
    public Offer.DescriptionData getDescriptionData() {
        return descriptionData;
    }

    /**
     * Sets the value of the descriptionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offer.DescriptionData }
     *     
     */
    public void setDescriptionData(Offer.DescriptionData value) {
        this.descriptionData = value;
    }

    /**
     * Gets the value of the additionalData property.
     * 
     * @return
     *     possible object is
     *     {@link Offer.AdditionalData }
     *     
     */
    public Offer.AdditionalData getAdditionalData() {
        return additionalData;
    }

    /**
     * Sets the value of the additionalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offer.AdditionalData }
     *     
     */
    public void setAdditionalData(Offer.AdditionalData value) {
        this.additionalData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='lax' maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class AdditionalData {

        @XmlAnyElement(lax = true)
        protected List<Object> any;

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * {@link Object }
         * 
         * 
         */
        public List<Object> getAny() {
            if (any == null) {
                any = new ArrayList<Object>();
            }
            return this.any;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="can_be_giftmessaged" type="{}BooleanValue" minOccurs="0"/>
     *         &lt;element name="can_be_giftwrapped" type="{}BooleanValue" minOccurs="0"/>
     *         &lt;element name="ean" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="value" type="{}StandardIdString" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="delete" type="{}BooleanType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="isbn" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="value">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
     *                         &lt;minLength value="10"/>
     *                         &lt;maxLength value="13"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="delete" type="{}BooleanType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="offering_condition" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="value" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
     *                         &lt;enumeration value="New"/>
     *                         &lt;enumeration value="Used"/>
     *                         &lt;enumeration value="Collectible"/>
     *                         &lt;enumeration value="Refurbished"/>
     *                         &lt;enumeration value="Club"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="delete" type="{}BooleanType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="offering_subcondition" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="value" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
     *                         &lt;enumeration value="New"/>
     *                         &lt;enumeration value="LikeNew"/>
     *                         &lt;enumeration value="VeryGood"/>
     *                         &lt;enumeration value="Good"/>
     *                         &lt;enumeration value="Acceptable"/>
     *                         &lt;enumeration value="Refurbished"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="delete" type="{}BooleanType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="product_tax_code" type="{}StringValue" minOccurs="0"/>
     *         &lt;element name="upc" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="value" type="{}StandardIdString" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="delete" type="{}BooleanType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "canBeGiftmessaged",
        "canBeGiftwrapped",
        "ean",
        "isbn",
        "offeringCondition",
        "offeringSubcondition",
        "productTaxCode",
        "upc"
    })
    public static class DescriptionData {

        @XmlElement(name = "can_be_giftmessaged")
        protected BooleanValue canBeGiftmessaged;
        @XmlElement(name = "can_be_giftwrapped")
        protected BooleanValue canBeGiftwrapped;
        protected Offer.DescriptionData.Ean ean;
        protected Offer.DescriptionData.Isbn isbn;
        @XmlElement(name = "offering_condition")
        protected Offer.DescriptionData.OfferingCondition offeringCondition;
        @XmlElement(name = "offering_subcondition")
        protected Offer.DescriptionData.OfferingSubcondition offeringSubcondition;
        @XmlElement(name = "product_tax_code")
        protected StringValue productTaxCode;
        protected Offer.DescriptionData.Upc upc;

        /**
         * Gets the value of the canBeGiftmessaged property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanValue }
         *     
         */
        public BooleanValue getCanBeGiftmessaged() {
            return canBeGiftmessaged;
        }

        /**
         * Sets the value of the canBeGiftmessaged property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanValue }
         *     
         */
        public void setCanBeGiftmessaged(BooleanValue value) {
            this.canBeGiftmessaged = value;
        }

        /**
         * Gets the value of the canBeGiftwrapped property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanValue }
         *     
         */
        public BooleanValue getCanBeGiftwrapped() {
            return canBeGiftwrapped;
        }

        /**
         * Sets the value of the canBeGiftwrapped property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanValue }
         *     
         */
        public void setCanBeGiftwrapped(BooleanValue value) {
            this.canBeGiftwrapped = value;
        }

        /**
         * Gets the value of the ean property.
         * 
         * @return
         *     possible object is
         *     {@link Offer.DescriptionData.Ean }
         *     
         */
        public Offer.DescriptionData.Ean getEan() {
            return ean;
        }

        /**
         * Sets the value of the ean property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offer.DescriptionData.Ean }
         *     
         */
        public void setEan(Offer.DescriptionData.Ean value) {
            this.ean = value;
        }

        /**
         * Gets the value of the isbn property.
         * 
         * @return
         *     possible object is
         *     {@link Offer.DescriptionData.Isbn }
         *     
         */
        public Offer.DescriptionData.Isbn getIsbn() {
            return isbn;
        }

        /**
         * Sets the value of the isbn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offer.DescriptionData.Isbn }
         *     
         */
        public void setIsbn(Offer.DescriptionData.Isbn value) {
            this.isbn = value;
        }

        /**
         * Gets the value of the offeringCondition property.
         * 
         * @return
         *     possible object is
         *     {@link Offer.DescriptionData.OfferingCondition }
         *     
         */
        public Offer.DescriptionData.OfferingCondition getOfferingCondition() {
            return offeringCondition;
        }

        /**
         * Sets the value of the offeringCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offer.DescriptionData.OfferingCondition }
         *     
         */
        public void setOfferingCondition(Offer.DescriptionData.OfferingCondition value) {
            this.offeringCondition = value;
        }

        /**
         * Gets the value of the offeringSubcondition property.
         * 
         * @return
         *     possible object is
         *     {@link Offer.DescriptionData.OfferingSubcondition }
         *     
         */
        public Offer.DescriptionData.OfferingSubcondition getOfferingSubcondition() {
            return offeringSubcondition;
        }

        /**
         * Sets the value of the offeringSubcondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offer.DescriptionData.OfferingSubcondition }
         *     
         */
        public void setOfferingSubcondition(Offer.DescriptionData.OfferingSubcondition value) {
            this.offeringSubcondition = value;
        }

        /**
         * Gets the value of the productTaxCode property.
         * 
         * @return
         *     possible object is
         *     {@link StringValue }
         *     
         */
        public StringValue getProductTaxCode() {
            return productTaxCode;
        }

        /**
         * Sets the value of the productTaxCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringValue }
         *     
         */
        public void setProductTaxCode(StringValue value) {
            this.productTaxCode = value;
        }

        /**
         * Gets the value of the upc property.
         * 
         * @return
         *     possible object is
         *     {@link Offer.DescriptionData.Upc }
         *     
         */
        public Offer.DescriptionData.Upc getUpc() {
            return upc;
        }

        /**
         * Sets the value of the upc property.
         * 
         * @param value
         *     allowed object is
         *     {@link Offer.DescriptionData.Upc }
         *     
         */
        public void setUpc(Offer.DescriptionData.Upc value) {
            this.upc = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="value" type="{}StandardIdString" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="delete" type="{}BooleanType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Ean {

            @XmlElement(required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected List<String> value;
            @XmlAttribute(name = "delete")
            protected BooleanType delete;

            /**
             * Gets the value of the value property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the value property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValue().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getValue() {
                if (value == null) {
                    value = new ArrayList<String>();
                }
                return this.value;
            }

            /**
             * Gets the value of the delete property.
             * 
             * @return
             *     possible object is
             *     {@link BooleanType }
             *     
             */
            public BooleanType getDelete() {
                return delete;
            }

            /**
             * Sets the value of the delete property.
             * 
             * @param value
             *     allowed object is
             *     {@link BooleanType }
             *     
             */
            public void setDelete(BooleanType value) {
                this.delete = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="value">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
         *               &lt;minLength value="10"/>
         *               &lt;maxLength value="13"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="delete" type="{}BooleanType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Isbn {

            @XmlElement(required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected String value;
            @XmlAttribute(name = "delete")
            protected BooleanType delete;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the delete property.
             * 
             * @return
             *     possible object is
             *     {@link BooleanType }
             *     
             */
            public BooleanType getDelete() {
                return delete;
            }

            /**
             * Sets the value of the delete property.
             * 
             * @param value
             *     allowed object is
             *     {@link BooleanType }
             *     
             */
            public void setDelete(BooleanType value) {
                this.delete = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="value" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
         *               &lt;enumeration value="New"/>
         *               &lt;enumeration value="Used"/>
         *               &lt;enumeration value="Collectible"/>
         *               &lt;enumeration value="Refurbished"/>
         *               &lt;enumeration value="Club"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="delete" type="{}BooleanType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class OfferingCondition {

            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected String value;
            @XmlAttribute(name = "delete")
            protected BooleanType delete;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the delete property.
             * 
             * @return
             *     possible object is
             *     {@link BooleanType }
             *     
             */
            public BooleanType getDelete() {
                return delete;
            }

            /**
             * Sets the value of the delete property.
             * 
             * @param value
             *     allowed object is
             *     {@link BooleanType }
             *     
             */
            public void setDelete(BooleanType value) {
                this.delete = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="value" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
         *               &lt;enumeration value="New"/>
         *               &lt;enumeration value="LikeNew"/>
         *               &lt;enumeration value="VeryGood"/>
         *               &lt;enumeration value="Good"/>
         *               &lt;enumeration value="Acceptable"/>
         *               &lt;enumeration value="Refurbished"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="delete" type="{}BooleanType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class OfferingSubcondition {

            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected String value;
            @XmlAttribute(name = "delete")
            protected BooleanType delete;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the delete property.
             * 
             * @return
             *     possible object is
             *     {@link BooleanType }
             *     
             */
            public BooleanType getDelete() {
                return delete;
            }

            /**
             * Sets the value of the delete property.
             * 
             * @param value
             *     allowed object is
             *     {@link BooleanType }
             *     
             */
            public void setDelete(BooleanType value) {
                this.delete = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="value" type="{}StandardIdString" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="delete" type="{}BooleanType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Upc {

            @XmlElement(required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected List<String> value;
            @XmlAttribute(name = "delete")
            protected BooleanType delete;

            /**
             * Gets the value of the value property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the value property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValue().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getValue() {
                if (value == null) {
                    value = new ArrayList<String>();
                }
                return this.value;
            }

            /**
             * Gets the value of the delete property.
             * 
             * @return
             *     possible object is
             *     {@link BooleanType }
             *     
             */
            public BooleanType getDelete() {
                return delete;
            }

            /**
             * Sets the value of the delete property.
             * 
             * @param value
             *     allowed object is
             *     {@link BooleanType }
             *     
             */
            public void setDelete(BooleanType value) {
                this.delete = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="launch_date" type="{}DateValue" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="market_name" use="required" type="{}ItemStringNotNull" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class MarketplaceData {

        @XmlElement(name = "launch_date")
        protected DateValue launchDate;
        @XmlAttribute(name = "market_name", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String marketName;

        /**
         * Gets the value of the launchDate property.
         * 
         * @return
         *     possible object is
         *     {@link DateValue }
         *     
         */
        public DateValue getLaunchDate() {
            return launchDate;
        }

        /**
         * Sets the value of the launchDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateValue }
         *     
         */
        public void setLaunchDate(DateValue value) {
            this.launchDate = value;
        }

        /**
         * Gets the value of the marketName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMarketName() {
            return marketName;
        }

        /**
         * Sets the value of the marketName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMarketName(String value) {
            this.marketName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="value" type="{}ItemFortyStringNotNull"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Sku {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
