//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:15:27 PM EDT 
//


package API.amazon.mws.xml.JAXB;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Language" type="{}LanguageType" minOccurs="0"/>
 *         &lt;element name="OrderStatus" type="{}String"/>
 *         &lt;element name="OrderChannel" type="{}String" minOccurs="0"/>
 *         &lt;element ref="{}AmazonOrderID"/>
 *         &lt;element ref="{}MarketplaceName"/>
 *         &lt;element ref="{}AmazonCustomerID"/>
 *         &lt;element name="AmazonSessionID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{3}-\d{7}-\d{7}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="CustomerOrderInfo" maxOccurs="10" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Type" type="{}StringNotNull"/>
 *                   &lt;element name="Value" type="{}StringNotNull"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BillingData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BuyerEmailAddress">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *                         &lt;pattern value="[^@]+@[^@\.]+(\.[^@\.]+)+"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="BuyerName" type="{}String"/>
 *                   &lt;element name="BuyerPhoneNumber" type="{}String"/>
 *                   &lt;element name="PaymentData" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Type" type="{}StringNotNull"/>
 *                             &lt;element name="Identifier" type="{}StringNotNull" minOccurs="0"/>
 *                             &lt;element name="Issuer" type="{}StringNotNull" minOccurs="0"/>
 *                             &lt;element name="Tail" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="\d{4}"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}gYearMonth" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{}Address" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Promotion" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{}StringNotNull"/>
 *                   &lt;element name="ID" type="{}String"/>
 *                   &lt;element name="Amount" type="{}CurrencyAmount"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FulfillmentData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}FulfillmentMethod" minOccurs="0"/>
 *                   &lt;element ref="{}ShipOption"/>
 *                   &lt;element ref="{}Address" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Item" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}AmazonOrderItemCode"/>
 *                   &lt;element ref="{}SKU"/>
 *                   &lt;element name="Title" type="{}LongString"/>
 *                   &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="ItemPrice" type="{}CurrencyAmount"/>
 *                   &lt;element name="GiftWrapLevel" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="GiftMessageText" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="500"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "language",
    "orderStatus",
    "orderChannel",
    "amazonOrderID",
    "marketplaceName",
    "amazonCustomerID",
    "amazonSessionID",
    "orderDate",
    "customerOrderInfo",
    "billingData",
    "promotion",
    "fulfillmentData",
    "item"
})
@XmlRootElement(name = "OrderNotificationReport")
public class OrderNotificationReport {

    @XmlElement(name = "Language")
    protected LanguageType language;
    @XmlElement(name = "OrderStatus", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderStatus;
    @XmlElement(name = "OrderChannel")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String orderChannel;
    @XmlElement(name = "AmazonOrderID", required = true)
    protected String amazonOrderID;
    @XmlElement(name = "MarketplaceName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String marketplaceName;
    @XmlElement(name = "AmazonCustomerID", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String amazonCustomerID;
    @XmlElement(name = "AmazonSessionID", required = true)
    protected String amazonSessionID;
    @XmlElement(name = "OrderDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar orderDate;
    @XmlElement(name = "CustomerOrderInfo")
    protected List<OrderNotificationReport.CustomerOrderInfo> customerOrderInfo;
    @XmlElement(name = "BillingData", required = true)
    protected OrderNotificationReport.BillingData billingData;
    @XmlElement(name = "Promotion")
    protected List<OrderNotificationReport.Promotion> promotion;
    @XmlElement(name = "FulfillmentData", required = true)
    protected OrderNotificationReport.FulfillmentData fulfillmentData;
    @XmlElement(name = "Item", required = true)
    protected List<OrderNotificationReport.Item> item;

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageType }
     *     
     */
    public LanguageType getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageType }
     *     
     */
    public void setLanguage(LanguageType value) {
        this.language = value;
    }

    /**
     * Gets the value of the orderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * Sets the value of the orderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderStatus(String value) {
        this.orderStatus = value;
    }

    /**
     * Gets the value of the orderChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderChannel() {
        return orderChannel;
    }

    /**
     * Sets the value of the orderChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderChannel(String value) {
        this.orderChannel = value;
    }

    /**
     * Gets the value of the amazonOrderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmazonOrderID() {
        return amazonOrderID;
    }

    /**
     * Sets the value of the amazonOrderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmazonOrderID(String value) {
        this.amazonOrderID = value;
    }

    /**
     * Gets the value of the marketplaceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketplaceName() {
        return marketplaceName;
    }

    /**
     * Sets the value of the marketplaceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketplaceName(String value) {
        this.marketplaceName = value;
    }

    /**
     * Gets the value of the amazonCustomerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmazonCustomerID() {
        return amazonCustomerID;
    }

    /**
     * Sets the value of the amazonCustomerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmazonCustomerID(String value) {
        this.amazonCustomerID = value;
    }

    /**
     * Gets the value of the amazonSessionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmazonSessionID() {
        return amazonSessionID;
    }

    /**
     * Sets the value of the amazonSessionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmazonSessionID(String value) {
        this.amazonSessionID = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderDate(XMLGregorianCalendar value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the customerOrderInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerOrderInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerOrderInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderNotificationReport.CustomerOrderInfo }
     * 
     * 
     */
    public List<OrderNotificationReport.CustomerOrderInfo> getCustomerOrderInfo() {
        if (customerOrderInfo == null) {
            customerOrderInfo = new ArrayList<OrderNotificationReport.CustomerOrderInfo>();
        }
        return this.customerOrderInfo;
    }

    /**
     * Gets the value of the billingData property.
     * 
     * @return
     *     possible object is
     *     {@link OrderNotificationReport.BillingData }
     *     
     */
    public OrderNotificationReport.BillingData getBillingData() {
        return billingData;
    }

    /**
     * Sets the value of the billingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderNotificationReport.BillingData }
     *     
     */
    public void setBillingData(OrderNotificationReport.BillingData value) {
        this.billingData = value;
    }

    /**
     * Gets the value of the promotion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderNotificationReport.Promotion }
     * 
     * 
     */
    public List<OrderNotificationReport.Promotion> getPromotion() {
        if (promotion == null) {
            promotion = new ArrayList<OrderNotificationReport.Promotion>();
        }
        return this.promotion;
    }

    /**
     * Gets the value of the fulfillmentData property.
     * 
     * @return
     *     possible object is
     *     {@link OrderNotificationReport.FulfillmentData }
     *     
     */
    public OrderNotificationReport.FulfillmentData getFulfillmentData() {
        return fulfillmentData;
    }

    /**
     * Sets the value of the fulfillmentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderNotificationReport.FulfillmentData }
     *     
     */
    public void setFulfillmentData(OrderNotificationReport.FulfillmentData value) {
        this.fulfillmentData = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderNotificationReport.Item }
     * 
     * 
     */
    public List<OrderNotificationReport.Item> getItem() {
        if (item == null) {
            item = new ArrayList<OrderNotificationReport.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BuyerEmailAddress">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
     *               &lt;pattern value="[^@]+@[^@\.]+(\.[^@\.]+)+"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="BuyerName" type="{}String"/>
     *         &lt;element name="BuyerPhoneNumber" type="{}String"/>
     *         &lt;element name="PaymentData" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Type" type="{}StringNotNull"/>
     *                   &lt;element name="Identifier" type="{}StringNotNull" minOccurs="0"/>
     *                   &lt;element name="Issuer" type="{}StringNotNull" minOccurs="0"/>
     *                   &lt;element name="Tail" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="\d{4}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}gYearMonth" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{}Address" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "buyerEmailAddress",
        "buyerName",
        "buyerPhoneNumber",
        "paymentData",
        "address"
    })
    public static class BillingData {

        @XmlElement(name = "BuyerEmailAddress", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String buyerEmailAddress;
        @XmlElement(name = "BuyerName", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String buyerName;
        @XmlElement(name = "BuyerPhoneNumber", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String buyerPhoneNumber;
        @XmlElement(name = "PaymentData")
        protected List<OrderNotificationReport.BillingData.PaymentData> paymentData;
        @XmlElement(name = "Address")
        protected AddressType address;

        /**
         * Gets the value of the buyerEmailAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuyerEmailAddress() {
            return buyerEmailAddress;
        }

        /**
         * Sets the value of the buyerEmailAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuyerEmailAddress(String value) {
            this.buyerEmailAddress = value;
        }

        /**
         * Gets the value of the buyerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuyerName() {
            return buyerName;
        }

        /**
         * Sets the value of the buyerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuyerName(String value) {
            this.buyerName = value;
        }

        /**
         * Gets the value of the buyerPhoneNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuyerPhoneNumber() {
            return buyerPhoneNumber;
        }

        /**
         * Sets the value of the buyerPhoneNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuyerPhoneNumber(String value) {
            this.buyerPhoneNumber = value;
        }

        /**
         * Gets the value of the paymentData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the paymentData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPaymentData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderNotificationReport.BillingData.PaymentData }
         * 
         * 
         */
        public List<OrderNotificationReport.BillingData.PaymentData> getPaymentData() {
            if (paymentData == null) {
                paymentData = new ArrayList<OrderNotificationReport.BillingData.PaymentData>();
            }
            return this.paymentData;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link AddressType }
         *     
         */
        public AddressType getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressType }
         *     
         */
        public void setAddress(AddressType value) {
            this.address = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Type" type="{}StringNotNull"/>
         *         &lt;element name="Identifier" type="{}StringNotNull" minOccurs="0"/>
         *         &lt;element name="Issuer" type="{}StringNotNull" minOccurs="0"/>
         *         &lt;element name="Tail" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="\d{4}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ExpirationDate" type="{http://www.w3.org/2001/XMLSchema}gYearMonth" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "type",
            "identifier",
            "issuer",
            "tail",
            "expirationDate"
        })
        public static class PaymentData {

            @XmlElement(name = "Type", required = true)
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected String type;
            @XmlElement(name = "Identifier")
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected String identifier;
            @XmlElement(name = "Issuer")
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            protected String issuer;
            @XmlElement(name = "Tail")
            protected String tail;
            @XmlElement(name = "ExpirationDate")
            @XmlSchemaType(name = "gYearMonth")
            protected XMLGregorianCalendar expirationDate;

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the identifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdentifier() {
                return identifier;
            }

            /**
             * Sets the value of the identifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdentifier(String value) {
                this.identifier = value;
            }

            /**
             * Gets the value of the issuer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIssuer() {
                return issuer;
            }

            /**
             * Sets the value of the issuer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIssuer(String value) {
                this.issuer = value;
            }

            /**
             * Gets the value of the tail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTail() {
                return tail;
            }

            /**
             * Sets the value of the tail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTail(String value) {
                this.tail = value;
            }

            /**
             * Gets the value of the expirationDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getExpirationDate() {
                return expirationDate;
            }

            /**
             * Sets the value of the expirationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setExpirationDate(XMLGregorianCalendar value) {
                this.expirationDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Type" type="{}StringNotNull"/>
     *         &lt;element name="Value" type="{}StringNotNull"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "value"
    })
    public static class CustomerOrderInfo {

        @XmlElement(name = "Type", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String type;
        @XmlElement(name = "Value", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String value;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}FulfillmentMethod" minOccurs="0"/>
     *         &lt;element ref="{}ShipOption"/>
     *         &lt;element ref="{}Address" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fulfillmentMethod",
        "shipOption",
        "address"
    })
    public static class FulfillmentData {

        @XmlElement(name = "FulfillmentMethod")
        protected String fulfillmentMethod;
        @XmlElement(name = "ShipOption", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String shipOption;
        @XmlElement(name = "Address")
        protected AddressType address;

        /**
         * Gets the value of the fulfillmentMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFulfillmentMethod() {
            return fulfillmentMethod;
        }

        /**
         * Sets the value of the fulfillmentMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFulfillmentMethod(String value) {
            this.fulfillmentMethod = value;
        }

        /**
         * Gets the value of the shipOption property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShipOption() {
            return shipOption;
        }

        /**
         * Sets the value of the shipOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShipOption(String value) {
            this.shipOption = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link AddressType }
         *     
         */
        public AddressType getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressType }
         *     
         */
        public void setAddress(AddressType value) {
            this.address = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}AmazonOrderItemCode"/>
     *         &lt;element ref="{}SKU"/>
     *         &lt;element name="Title" type="{}LongString"/>
     *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="ItemPrice" type="{}CurrencyAmount"/>
     *         &lt;element name="GiftWrapLevel" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="GiftMessageText" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="500"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "amazonOrderItemCode",
        "sku",
        "title",
        "quantity",
        "itemPrice",
        "giftWrapLevel",
        "giftMessageText"
    })
    public static class Item {

        @XmlElement(name = "AmazonOrderItemCode", required = true)
        protected String amazonOrderItemCode;
        @XmlElement(name = "SKU", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String sku;
        @XmlElement(name = "Title", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String title;
        @XmlElement(name = "Quantity", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger quantity;
        @XmlElement(name = "ItemPrice", required = true)
        protected CurrencyAmount itemPrice;
        @XmlElement(name = "GiftWrapLevel")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String giftWrapLevel;
        @XmlElement(name = "GiftMessageText")
        protected String giftMessageText;

        /**
         * Gets the value of the amazonOrderItemCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmazonOrderItemCode() {
            return amazonOrderItemCode;
        }

        /**
         * Sets the value of the amazonOrderItemCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmazonOrderItemCode(String value) {
            this.amazonOrderItemCode = value;
        }

        /**
         * Gets the value of the sku property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSKU() {
            return sku;
        }

        /**
         * Sets the value of the sku property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSKU(String value) {
            this.sku = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getQuantity() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setQuantity(BigInteger value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the itemPrice property.
         * 
         * @return
         *     possible object is
         *     {@link CurrencyAmount }
         *     
         */
        public CurrencyAmount getItemPrice() {
            return itemPrice;
        }

        /**
         * Sets the value of the itemPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link CurrencyAmount }
         *     
         */
        public void setItemPrice(CurrencyAmount value) {
            this.itemPrice = value;
        }

        /**
         * Gets the value of the giftWrapLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftWrapLevel() {
            return giftWrapLevel;
        }

        /**
         * Sets the value of the giftWrapLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftWrapLevel(String value) {
            this.giftWrapLevel = value;
        }

        /**
         * Gets the value of the giftMessageText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiftMessageText() {
            return giftMessageText;
        }

        /**
         * Sets the value of the giftMessageText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiftMessageText(String value) {
            this.giftMessageText = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Name" type="{}StringNotNull"/>
     *         &lt;element name="ID" type="{}String"/>
     *         &lt;element name="Amount" type="{}CurrencyAmount"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "id",
        "amount"
    })
    public static class Promotion {

        @XmlElement(name = "Name", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String name;
        @XmlElement(name = "ID", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String id;
        @XmlElement(name = "Amount", required = true)
        protected CurrencyAmount amount;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link CurrencyAmount }
         *     
         */
        public CurrencyAmount getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link CurrencyAmount }
         *     
         */
        public void setAmount(CurrencyAmount value) {
            this.amount = value;
        }

    }

}
