//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:15:27 PM EDT 
//


package API.amazon.mws.xml.JAXB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sku">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="value" type="{}ItemFortyStringNotNull"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="asin">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="value" type="{}StandardIdString"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PackageDimensions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="package_height" type="{}DimensionValue"/>
 *                   &lt;element name="package_length" type="{}DimensionValue"/>
 *                   &lt;element name="package_width" type="{}DimensionValue"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="package_weight" type="{}WeightValue" minOccurs="0"/>
 *         &lt;element name="item_package_conveyability" type="{}ConveyabilityValue" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sku",
    "asin",
    "packageDimensions",
    "packageWeight",
    "itemPackageConveyability"
})
@XmlRootElement(name = "ReverseItem")
public class ReverseItem {

    @XmlElement(required = true)
    protected ReverseItem.Sku sku;
    @XmlElement(required = true)
    protected ReverseItem.Asin asin;
    @XmlElement(name = "PackageDimensions")
    protected ReverseItem.PackageDimensions packageDimensions;
    @XmlElement(name = "package_weight")
    protected WeightValue packageWeight;
    @XmlElement(name = "item_package_conveyability")
    protected ConveyabilityValue itemPackageConveyability;

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link ReverseItem.Sku }
     *     
     */
    public ReverseItem.Sku getSku() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReverseItem.Sku }
     *     
     */
    public void setSku(ReverseItem.Sku value) {
        this.sku = value;
    }

    /**
     * Gets the value of the asin property.
     * 
     * @return
     *     possible object is
     *     {@link ReverseItem.Asin }
     *     
     */
    public ReverseItem.Asin getAsin() {
        return asin;
    }

    /**
     * Sets the value of the asin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReverseItem.Asin }
     *     
     */
    public void setAsin(ReverseItem.Asin value) {
        this.asin = value;
    }

    /**
     * Gets the value of the packageDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link ReverseItem.PackageDimensions }
     *     
     */
    public ReverseItem.PackageDimensions getPackageDimensions() {
        return packageDimensions;
    }

    /**
     * Sets the value of the packageDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReverseItem.PackageDimensions }
     *     
     */
    public void setPackageDimensions(ReverseItem.PackageDimensions value) {
        this.packageDimensions = value;
    }

    /**
     * Gets the value of the packageWeight property.
     * 
     * @return
     *     possible object is
     *     {@link WeightValue }
     *     
     */
    public WeightValue getPackageWeight() {
        return packageWeight;
    }

    /**
     * Sets the value of the packageWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightValue }
     *     
     */
    public void setPackageWeight(WeightValue value) {
        this.packageWeight = value;
    }

    /**
     * Gets the value of the itemPackageConveyability property.
     * 
     * @return
     *     possible object is
     *     {@link ConveyabilityValue }
     *     
     */
    public ConveyabilityValue getItemPackageConveyability() {
        return itemPackageConveyability;
    }

    /**
     * Sets the value of the itemPackageConveyability property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConveyabilityValue }
     *     
     */
    public void setItemPackageConveyability(ConveyabilityValue value) {
        this.itemPackageConveyability = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="value" type="{}StandardIdString"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Asin {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="package_height" type="{}DimensionValue"/>
     *         &lt;element name="package_length" type="{}DimensionValue"/>
     *         &lt;element name="package_width" type="{}DimensionValue"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "packageHeight",
        "packageLength",
        "packageWidth"
    })
    public static class PackageDimensions {

        @XmlElement(name = "package_height", required = true)
        protected DimensionValue packageHeight;
        @XmlElement(name = "package_length", required = true)
        protected DimensionValue packageLength;
        @XmlElement(name = "package_width", required = true)
        protected DimensionValue packageWidth;

        /**
         * Gets the value of the packageHeight property.
         * 
         * @return
         *     possible object is
         *     {@link DimensionValue }
         *     
         */
        public DimensionValue getPackageHeight() {
            return packageHeight;
        }

        /**
         * Sets the value of the packageHeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link DimensionValue }
         *     
         */
        public void setPackageHeight(DimensionValue value) {
            this.packageHeight = value;
        }

        /**
         * Gets the value of the packageLength property.
         * 
         * @return
         *     possible object is
         *     {@link DimensionValue }
         *     
         */
        public DimensionValue getPackageLength() {
            return packageLength;
        }

        /**
         * Sets the value of the packageLength property.
         * 
         * @param value
         *     allowed object is
         *     {@link DimensionValue }
         *     
         */
        public void setPackageLength(DimensionValue value) {
            this.packageLength = value;
        }

        /**
         * Gets the value of the packageWidth property.
         * 
         * @return
         *     possible object is
         *     {@link DimensionValue }
         *     
         */
        public DimensionValue getPackageWidth() {
            return packageWidth;
        }

        /**
         * Sets the value of the packageWidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link DimensionValue }
         *     
         */
        public void setPackageWidth(DimensionValue value) {
            this.packageWidth = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="value" type="{}ItemFortyStringNotNull"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Sku {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
