//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:15:27 PM EDT 
//


package API.amazon.mws.xml.JAXB;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="stone_color" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_clarity" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_cut" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_culet" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_depth_percentage" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="value" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="14"/>
 *                         &lt;fractionDigits value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="delete" type="{}BooleanType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stone_fluorescence" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_girdle" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_polish" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_shape" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_symmetry" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="stone_table_percentage" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="value" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="14"/>
 *                         &lt;fractionDigits value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="delete" type="{}BooleanType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stone_weight" type="{}JewelryWeightValue" minOccurs="0"/>
 *         &lt;element name="gem_type" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="inscription" type="{}StringValue" minOccurs="0"/>
 *         &lt;element name="is_lab_created" type="{}BooleanValue" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Stone")
public class Stone {

    @XmlElement(name = "stone_color")
    protected StringValue stoneColor;
    @XmlElement(name = "stone_clarity")
    protected StringValue stoneClarity;
    @XmlElement(name = "stone_cut")
    protected StringValue stoneCut;
    @XmlElement(name = "stone_culet")
    protected StringValue stoneCulet;
    @XmlElement(name = "stone_depth_percentage")
    protected Stone.StoneDepthPercentage stoneDepthPercentage;
    @XmlElement(name = "stone_fluorescence")
    protected StringValue stoneFluorescence;
    @XmlElement(name = "stone_girdle")
    protected StringValue stoneGirdle;
    @XmlElement(name = "stone_polish")
    protected StringValue stonePolish;
    @XmlElement(name = "stone_shape")
    protected StringValue stoneShape;
    @XmlElement(name = "stone_symmetry")
    protected StringValue stoneSymmetry;
    @XmlElement(name = "stone_table_percentage")
    protected Stone.StoneTablePercentage stoneTablePercentage;
    @XmlElement(name = "stone_weight")
    protected JewelryWeightValue stoneWeight;
    @XmlElement(name = "gem_type")
    protected StringValue gemType;
    protected StringValue inscription;
    @XmlElement(name = "is_lab_created")
    protected BooleanValue isLabCreated;

    /**
     * Gets the value of the stoneColor property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStoneColor() {
        return stoneColor;
    }

    /**
     * Sets the value of the stoneColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStoneColor(StringValue value) {
        this.stoneColor = value;
    }

    /**
     * Gets the value of the stoneClarity property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStoneClarity() {
        return stoneClarity;
    }

    /**
     * Sets the value of the stoneClarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStoneClarity(StringValue value) {
        this.stoneClarity = value;
    }

    /**
     * Gets the value of the stoneCut property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStoneCut() {
        return stoneCut;
    }

    /**
     * Sets the value of the stoneCut property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStoneCut(StringValue value) {
        this.stoneCut = value;
    }

    /**
     * Gets the value of the stoneCulet property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStoneCulet() {
        return stoneCulet;
    }

    /**
     * Sets the value of the stoneCulet property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStoneCulet(StringValue value) {
        this.stoneCulet = value;
    }

    /**
     * Gets the value of the stoneDepthPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Stone.StoneDepthPercentage }
     *     
     */
    public Stone.StoneDepthPercentage getStoneDepthPercentage() {
        return stoneDepthPercentage;
    }

    /**
     * Sets the value of the stoneDepthPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stone.StoneDepthPercentage }
     *     
     */
    public void setStoneDepthPercentage(Stone.StoneDepthPercentage value) {
        this.stoneDepthPercentage = value;
    }

    /**
     * Gets the value of the stoneFluorescence property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStoneFluorescence() {
        return stoneFluorescence;
    }

    /**
     * Sets the value of the stoneFluorescence property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStoneFluorescence(StringValue value) {
        this.stoneFluorescence = value;
    }

    /**
     * Gets the value of the stoneGirdle property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStoneGirdle() {
        return stoneGirdle;
    }

    /**
     * Sets the value of the stoneGirdle property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStoneGirdle(StringValue value) {
        this.stoneGirdle = value;
    }

    /**
     * Gets the value of the stonePolish property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStonePolish() {
        return stonePolish;
    }

    /**
     * Sets the value of the stonePolish property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStonePolish(StringValue value) {
        this.stonePolish = value;
    }

    /**
     * Gets the value of the stoneShape property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStoneShape() {
        return stoneShape;
    }

    /**
     * Sets the value of the stoneShape property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStoneShape(StringValue value) {
        this.stoneShape = value;
    }

    /**
     * Gets the value of the stoneSymmetry property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStoneSymmetry() {
        return stoneSymmetry;
    }

    /**
     * Sets the value of the stoneSymmetry property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStoneSymmetry(StringValue value) {
        this.stoneSymmetry = value;
    }

    /**
     * Gets the value of the stoneTablePercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Stone.StoneTablePercentage }
     *     
     */
    public Stone.StoneTablePercentage getStoneTablePercentage() {
        return stoneTablePercentage;
    }

    /**
     * Sets the value of the stoneTablePercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stone.StoneTablePercentage }
     *     
     */
    public void setStoneTablePercentage(Stone.StoneTablePercentage value) {
        this.stoneTablePercentage = value;
    }

    /**
     * Gets the value of the stoneWeight property.
     * 
     * @return
     *     possible object is
     *     {@link JewelryWeightValue }
     *     
     */
    public JewelryWeightValue getStoneWeight() {
        return stoneWeight;
    }

    /**
     * Sets the value of the stoneWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link JewelryWeightValue }
     *     
     */
    public void setStoneWeight(JewelryWeightValue value) {
        this.stoneWeight = value;
    }

    /**
     * Gets the value of the gemType property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getGemType() {
        return gemType;
    }

    /**
     * Sets the value of the gemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setGemType(StringValue value) {
        this.gemType = value;
    }

    /**
     * Gets the value of the inscription property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getInscription() {
        return inscription;
    }

    /**
     * Sets the value of the inscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setInscription(StringValue value) {
        this.inscription = value;
    }

    /**
     * Gets the value of the isLabCreated property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanValue }
     *     
     */
    public BooleanValue getIsLabCreated() {
        return isLabCreated;
    }

    /**
     * Sets the value of the isLabCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanValue }
     *     
     */
    public void setIsLabCreated(BooleanValue value) {
        this.isLabCreated = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="value" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="14"/>
     *               &lt;fractionDigits value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="delete" type="{}BooleanType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StoneDepthPercentage {

        protected BigDecimal value;
        @XmlAttribute(name = "delete")
        protected BooleanType delete;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the delete property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanType }
         *     
         */
        public BooleanType getDelete() {
            return delete;
        }

        /**
         * Sets the value of the delete property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanType }
         *     
         */
        public void setDelete(BooleanType value) {
            this.delete = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="value" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="14"/>
     *               &lt;fractionDigits value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="delete" type="{}BooleanType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StoneTablePercentage {

        protected BigDecimal value;
        @XmlAttribute(name = "delete")
        protected BooleanType delete;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the delete property.
         * 
         * @return
         *     possible object is
         *     {@link BooleanType }
         *     
         */
        public BooleanType getDelete() {
            return delete;
        }

        /**
         * Sets the value of the delete property.
         * 
         * @param value
         *     allowed object is
         *     {@link BooleanType }
         *     
         */
        public void setDelete(BooleanType value) {
            this.delete = value;
        }

    }

}
