package com.v3.dto;

// Generated Mar 1, 2014 3:23:41 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ColorMap generated by hbm2java
 */
@Entity
@Table(name = "color_map", catalog = "v3_inventory")
public class ColorMap implements java.io.Serializable {

	private Integer idColorMap;
	private Color color;
	private String colorMap;
	private Set<Shoe> shoes = new HashSet<Shoe>(0);

	public ColorMap() {
	}

	public ColorMap(Color color) {
		this.color = color;
	}

	public ColorMap(Color color, String colorMap) {
		this.color = color;
		this.colorMap = colorMap;
		this.shoes = shoes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_color_map", unique = true, nullable = false)
	public Integer getIdColorMap() {
		return this.idColorMap;
	}

	public void setIdColorMap(Integer idColorMap) {
		this.idColorMap = idColorMap;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_color", nullable = false)
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@Column(name = "color_map", length = 45)
	public String getColorMap() {
		return this.colorMap;
	}

	public void setColorMap(String colorMap) {
		this.colorMap = colorMap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "colorMap")
	public Set<Shoe> getShoes() {
		return this.shoes;
	}

	public void setShoes(Set<Shoe> shoes) {
		this.shoes = shoes;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return colorMap;
	}

}
