package com.v3.dto;

// Generated Mar 1, 2014 3:23:41 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "images", catalog = "v3_inventory")
public class Images implements java.io.Serializable {

	private Integer idImg;
	private String thumb;
	private String mainImg;
	private String img2;
	private String img3;
	private String img4;
	private String img5;
	private String img6;
	private String img7;
	private String img8;
	private Set<Shoe> shoes = new HashSet<Shoe>(0);

	public Images() {
	}

	public Images(String thumb, String mainImg, String img2, String img3,
			String img4, String img5, String img6, String img7, String img8,
			Set<Shoe> shoes) {
		this.thumb = thumb;
		this.mainImg = mainImg;
		this.img2 = img2;
		this.img3 = img3;
		this.img4 = img4;
		this.img5 = img5;
		this.img6 = img6;
		this.img7 = img7;
		this.img8 = img8;
		this.shoes = shoes;
	}

	public Images(String thumb) {
		this.thumb = thumb;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_img", unique = true, nullable = false)
	public Integer getIdImg() {
		return this.idImg;
	}

	public void setIdImg(Integer idImg) {
		this.idImg = idImg;
	}

	@Column(name = "thumb", length = 160)
	public String getThumb() {
		return this.thumb;
	}

	public void setThumb(String thumb) {
		this.thumb = thumb;
	}

	@Column(name = "main_img", length = 160)
	public String getMainImg() {
		return this.mainImg;
	}

	public void setMainImg(String mainImg) {
		this.mainImg = mainImg;
	}

	@Column(name = "img2", length = 160)
	public String getImg2() {
		return this.img2;
	}

	public void setImg2(String img2) {
		this.img2 = img2;
	}

	@Column(name = "img3", length = 160)
	public String getImg3() {
		return this.img3;
	}

	public void setImg3(String img3) {
		this.img3 = img3;
	}

	@Column(name = "img4", length = 160)
	public String getImg4() {
		return this.img4;
	}

	public void setImg4(String img4) {
		this.img4 = img4;
	}

	@Column(name = "img5", length = 160)
	public String getImg5() {
		return this.img5;
	}

	public void setImg5(String img5) {
		this.img5 = img5;
	}

	@Column(name = "img6", length = 160)
	public String getImg6() {
		return this.img6;
	}

	public void setImg6(String img6) {
		this.img6 = img6;
	}

	@Column(name = "img7", length = 160)
	public String getImg7() {
		return this.img7;
	}

	public void setImg7(String img7) {
		this.img7 = img7;
	}

	@Column(name = "img8", length = 160)
	public String getImg8() {
		return this.img8;
	}

	public void setImg8(String img8) {
		this.img8 = img8;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "images")
	public Set<Shoe> getShoes() {
		return this.shoes;
	}

	public void setShoes(Set<Shoe> shoes) {
		this.shoes = shoes;
	}

}
