package com.v3.dto;

// Generated Mar 1, 2014 3:23:41 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Lot generated by hbm2java
 */
@Entity
@Table(name = "lot", catalog = "v3_inventory", uniqueConstraints = @UniqueConstraint(columnNames = "lot"))
public class Lot implements java.io.Serializable {

	private Integer idLot;
	private String lot;
	private Date timeIn;
	private Set<Product> products = new HashSet<Product>(0);

	public Lot() {
	}

	public Lot(String lot, Date timeIn) {
		this.lot = lot;
		this.timeIn = timeIn;
	}

	public Lot(String lot, Date timeIn, Set<Product> products) {
		this.lot = lot;
		this.timeIn = timeIn;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_lot", unique = true, nullable = false)
	public Integer getIdLot() {
		return this.idLot;
	}

	public void setIdLot(Integer idLot) {
		this.idLot = idLot;
	}

	@Column(name = "lot", unique = true, nullable = false, length = 45)
	public String getLot() {
		return this.lot;
	}

	public void setLot(String lot) {
		this.lot = lot;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_in", nullable = false, length = 19)
	public Date getTimeIn() {
		return this.timeIn;
	}

	public void setTimeIn(Date timeIn) {
		this.timeIn = timeIn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lot")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
