package com.v3.dto;

// Generated Feb 22, 2014 3:49:27 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name = "order_item", catalog = "v3_inventory")
public class OrderItem implements java.io.Serializable {

	private String idOrderItem;
	private Order order;
	private String sku;
	private String title;
	private String qtyOrdered;
	private String qtyShipped;

	public OrderItem() {
	}

	public OrderItem(String idOrderItem, Order order, String sku, String title) {
		this.idOrderItem = idOrderItem;
		this.order = order;
		this.sku = sku;
		this.title = title;
	}

	public OrderItem(String idOrderItem, Order order, String sku, String title,
			String qtyOrdered, String qtyShipped) {
		this.idOrderItem = idOrderItem;
		this.order = order;
		this.sku = sku;
		this.title = title;
		this.qtyOrdered = qtyOrdered;
		this.qtyShipped = qtyShipped;
	}

	@Id
	@Column(name = "id_order_item", unique = true, nullable = false, length = 45)
	public String getIdOrderItem() {
		return this.idOrderItem;
	}

	public void setIdOrderItem(String idOrderItem) {
		this.idOrderItem = idOrderItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_order", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "sku", nullable = false, length = 45)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "qty_ordered", length = 45)
	public String getQtyOrdered() {
		return this.qtyOrdered;
	}

	public void setQtyOrdered(String qtyOrdered) {
		this.qtyOrdered = qtyOrdered;
	}

	@Column(name = "qty_shipped", length = 45)
	public String getQtyShipped() {
		return this.qtyShipped;
	}

	public void setQtyShipped(String qtyShipped) {
		this.qtyShipped = qtyShipped;
	}

}
