package com.v3.dto;

// Generated Mar 1, 2014 3:23:41 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "v3_inventory")
public class Order implements java.io.Serializable {

	private int idOrder;
	private Customer customer;
	private Channels channels;
	private String idOrderChannel;
	private String status;
	private Date purchasedDate;
	private Date lastUpdatedDate;

	public Order() {
	}

	public Order(int idOrder, Customer customer, Channels channels,
			String status) {
		this.idOrder = idOrder;
		this.customer = customer;
		this.channels = channels;
		this.status = status;
	}

	public Order(int idOrder, Customer customer, Channels channels,
			String idOrderChannel, String status, Date purchasedDate,
			Date lastUpdatedDate) {
		this.idOrder = idOrder;
		this.customer = customer;
		this.channels = channels;
		this.idOrderChannel = idOrderChannel;
		this.status = status;
		this.purchasedDate = purchasedDate;
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@Id
	@Column(name = "id_order", unique = true, nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_customer", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_channel", nullable = false)
	public Channels getChannels() {
		return this.channels;
	}

	public void setChannels(Channels channels) {
		this.channels = channels;
	}

	@Column(name = "id_order_channel", length = 45)
	public String getIdOrderChannel() {
		return this.idOrderChannel;
	}

	public void setIdOrderChannel(String idOrderChannel) {
		this.idOrderChannel = idOrderChannel;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchased_date", length = 19)
	public Date getPurchasedDate() {
		return this.purchasedDate;
	}

	public void setPurchasedDate(Date purchasedDate) {
		this.purchasedDate = purchasedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 19)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

}
