package com.v3.dto;

// Generated Feb 22, 2014 3:49:27 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShoeHasModels generated by hbm2java
 */
@Entity
@Table(name = "shoe_has_models", catalog = "v3_inventory")
public class ShoeHasModels implements java.io.Serializable {

	private int id;
	private ShoeModel shoeModel;

	public ShoeHasModels() {
	}

	public ShoeHasModels(int id, ShoeModel shoeModel) {
		this.id = id;
		this.shoeModel = shoeModel;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_model", nullable = false)
	public ShoeModel getShoeModel() {
		return this.shoeModel;
	}

	public void setShoeModel(ShoeModel shoeModel) {
		this.shoeModel = shoeModel;
	}

}
