package com.v3.dto;

// Generated Mar 1, 2014 3:23:41 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Size generated by hbm2java
 */
@Entity
@Table(name = "size", catalog = "v3_inventory")
public class Size implements java.io.Serializable {

	private Byte idSize;
	private String size;
	private Set<SizeMap> sizeMaps = new HashSet<SizeMap>(0);

	public Size() {
	}

	public Size(String size, Set<SizeMap> sizeMaps) {
		this.size = size;
		this.sizeMaps = sizeMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_size", unique = true, nullable = false)
	public Byte getIdSize() {
		return this.idSize;
	}

	public void setIdSize(Byte idSize) {
		this.idSize = idSize;
	}

	@Column(name = "size", length = 45)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "size")
	public Set<SizeMap> getSizeMaps() {
		return this.sizeMaps;
	}

	public void setSizeMaps(Set<SizeMap> sizeMaps) {
		this.sizeMaps = sizeMaps;
	}

}
