package com.v3.dto;

// Generated May 24, 2014 1:21:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SkuItemDef generated by hbm2java
 */
@Entity
@Table(name = "sku_item_def", catalog = "v3_inventory")
public class SkuItemDef implements java.io.Serializable {

	private SkuItemDefId id;

	public SkuItemDef() {
	}

	public SkuItemDef(SkuItemDefId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "skuItem", column = @Column(name = "SKU_Item", length = 13)),
			@AttributeOverride(name = "upc", column = @Column(name = "upc", nullable = false, length = 12)),
			@AttributeOverride(name = "idBrand", column = @Column(name = "id_brand", nullable = false)),
			@AttributeOverride(name = "idStyle", column = @Column(name = "id_style", nullable = false)),
			@AttributeOverride(name = "idSizeMap", column = @Column(name = "id_size_map")),
			@AttributeOverride(name = "idColorMap", column = @Column(name = "id_color_map")),
			@AttributeOverride(name = "idSize", column = @Column(name = "id_size")) })
	public SkuItemDefId getId() {
		return this.id;
	}

	public void setId(SkuItemDefId id) {
		this.id = id;
	}

}
