package com.v3.dto;

// Generated May 24, 2014 1:21:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SkuShoeView generated by hbm2java
 */
@Entity
@Table(name = "sku_shoe_view", catalog = "v3_inventory")
public class SkuShoeView implements java.io.Serializable {

	private SkuShoeViewId id;

	public SkuShoeView() {
	}

	public SkuShoeView(SkuShoeViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "skuItem", column = @Column(name = "SKU_Item", length = 13)),
			@AttributeOverride(name = "upc", column = @Column(name = "UPC", length = 12)),
			@AttributeOverride(name = "sku", column = @Column(name = "SKU", length = 6)),
			@AttributeOverride(name = "itemNumber", column = @Column(name = "Item_Number", length = 6)),
			@AttributeOverride(name = "brand", column = @Column(name = "Brand", nullable = false, length = 45)),
			@AttributeOverride(name = "style", column = @Column(name = "Style", nullable = false, length = 45)),
			@AttributeOverride(name = "colorMap", column = @Column(name = "Color_Map", length = 45)),
			@AttributeOverride(name = "color", column = @Column(name = "Color", length = 45)),
			@AttributeOverride(name = "sizeMap", column = @Column(name = "Size_Map", length = 45)),
			@AttributeOverride(name = "size", column = @Column(name = "Size", length = 45)),
			@AttributeOverride(name = "sortSize", column = @Column(name = "Sort_Size", nullable = false)),
			@AttributeOverride(name = "inStock", column = @Column(name = "In_Stock", precision = 23, scale = 0)),
			@AttributeOverride(name = "material", column = @Column(name = "Material", nullable = false, length = 45)),
			@AttributeOverride(name = "shoeType", column = @Column(name = "Shoe_Type", nullable = false, length = 4)),
			@AttributeOverride(name = "description", column = @Column(name = "Description", nullable = false, length = 11)) })
	public SkuShoeViewId getId() {
		return this.id;
	}

	public void setId(SkuShoeViewId id) {
		this.id = id;
	}

}
