package com.v3.dto;

// Generated May 24, 2014 1:21:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SyncAmznProducts generated by hbm2java
 */
@Entity
@Table(name = "sync_amzn_products", catalog = "v3_inventory")
public class SyncAmznProducts implements java.io.Serializable {

	private SyncAmznProductsId id;
	private Integer qty;
	private Double price;
	private boolean isInDb;
	private Integer idBrand;
	private Integer idStyle;
	private Integer idSizeMap;
	private Integer idColorMap;
	private String upc;

	public SyncAmznProducts() {
	}

	public SyncAmznProducts(SyncAmznProductsId id, boolean isInDb) {
		this.id = id;
		this.isInDb = isInDb;
	}

	public SyncAmznProducts(SyncAmznProductsId id, Integer qty, Double price,
			boolean isInDb, Integer idBrand, Integer idStyle,
			Integer idSizeMap, Integer idColorMap, String upc) {
		this.id = id;
		this.qty = qty;
		this.price = price;
		this.isInDb = isInDb;
		this.idBrand = idBrand;
		this.idStyle = idStyle;
		this.idSizeMap = idSizeMap;
		this.idColorMap = idColorMap;
		this.upc = upc;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "asin", column = @Column(name = "asin", nullable = false, length = 15)),
			@AttributeOverride(name = "sku", column = @Column(name = "sku", nullable = false, length = 30)) })
	public SyncAmznProductsId getId() {
		return this.id;
	}

	public void setId(SyncAmznProductsId id) {
		this.id = id;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "is_in_db", nullable = false)
	public boolean isIsInDb() {
		return this.isInDb;
	}

	public void setIsInDb(boolean isInDb) {
		this.isInDb = isInDb;
	}

	@Column(name = "id_brand")
	public Integer getIdBrand() {
		return this.idBrand;
	}

	public void setIdBrand(Integer idBrand) {
		this.idBrand = idBrand;
	}

	@Column(name = "id_style")
	public Integer getIdStyle() {
		return this.idStyle;
	}

	public void setIdStyle(Integer idStyle) {
		this.idStyle = idStyle;
	}

	@Column(name = "id_size_map")
	public Integer getIdSizeMap() {
		return this.idSizeMap;
	}

	public void setIdSizeMap(Integer idSizeMap) {
		this.idSizeMap = idSizeMap;
	}

	@Column(name = "id_color_map")
	public Integer getIdColorMap() {
		return this.idColorMap;
	}

	public void setIdColorMap(Integer idColorMap) {
		this.idColorMap = idColorMap;
	}

	@Column(name = "upc", length = 12)
	public String getUpc() {
		return this.upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

}
